---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${artifactId}
data:
  application.properties: |
    simple.welcome-message=OKCM
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ${artifactId}
    app.kubernetes.io/version: ${version}
    camel.apache.org/integration: ${artifactId}
  name: ${artifactId}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: ${artifactId}
    app.kubernetes.io/version: ${version}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${artifactId}
  labels:
      app.kubernetes.io/name: ${artifactId}
      app.kubernetes.io/version: ${version}
      camel.apache.org/integration: ${artifactId}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: ${version}
      app.kubernetes.io/name: ${artifactId}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${artifactId}
        app.kubernetes.io/version: ${version}
        camel.apache.org/integration: ${artifactId}
    spec:
      containers:
      - name: ${artifactId}
        image: gcr.io/adtsys/${artifactId}:${version}
        imagePullPolicy: Always
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace              
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10  
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
        volumeMounts:
        - name: config
          mountPath: /deployments/config
      volumes:
      - name: config
        configMap:
          name: ${artifactId}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${artifactId}
  labels:
      app.kubernetes.io/name: ${artifactId}
      app.kubernetes.io/version: ${version}
      camel.apache.org/integration: ${artifactId}
spec:
  selector: 
    matchLabels:
      app.kubernetes.io/name: ${artifactId}
      app.kubernetes.io/version: ${version}
      camel.apache.org/integration: ${artifactId}
  endpoints:
  - port: http
    path: /q/metrics
    interval: 25s
    honorLabels: false
